---
- name: debian_dependencies | Debian lsb-release
  apt:
    name: lsb-release
    state: present
  tags:
    - lsb-release
    - lsb

- name: debian_dependencies | Install APT tools dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - aptitude
    - debian-archive-keyring
    - apt-transport-https
    - curl
    - ca-certificates
    - wget
    - sudo
