---
- name: debian_packages | Remove packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apt_remove_packages }}"

- name: debian_packages | Install default packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_default_packages }}"

- name: debian_packages | Install extra packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_extra_packages }}"
