---
- name: debian_update | Apt update list
  apt:
    update_cache: yes
    cache_valid_timei: "{{ omit if apt_sources_lists_default_result.changed or apt_sources_lists_extra_result.changed else apt_update_cache_valid_time|default(3600) }}"

- name: debian_update | Apt upgrade
  apt:
    upgrade: "{{ apt_upgrade_type|default('safe') }}"
  when: apt_upgrade
