---
- include: install_debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - packages
    - apt

- include: install_redhat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - packages
    - yum
