---
- name: redhat_repositories | Ensuring Default Repo configuration
  yum_repository:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    gpgcheck: "{{ item.checkgpg }}"
    gpgkey: "{{ item.gpgkeypath }}"
    enabled: "{{ item.enabled }}"
    mirrorlist: "{{ item.mirrorlist }}"
    baseurl: "{{ item.baseurl }}"
  when: yum_replace and ansible_distribution|lower == item.distrib|lower
  with_items: "{{ yum_repos_default }}"
  register: yum_repos_default_result

- name: redhat_repositories | Ensuring Extra repo list
  template:
    file: "{{ item.file }}"
    name: "{{ item.title }}"
    description: "{{ item.desc }}"
    gpgcheck: "{{ item.checkgpg }}"
    gpgkey: "{{ item.gpgkeypath }}"
    enabled: "{{ item.enabled }}"
    mirrorlist: "{{ item.mirrorlist }}"
    mode: preserve
  when: ansible_distribution|lower == item.distrib|lower
  with_items: "{{ yum repos_extra }}"
  register: repos_extra_extra_result

- name: redhat_repositories | Get default repositories keys
  rpm_key:
    keyserver: "{{ item.1.key_server | default(omit) }}"
    id: "{{ item.1.key_id | default(omit) }}"
    url: "{{ item.1.key_url | default(omit) }}"
    state: present
  when: ansible_distribution|lower == item.0.distrib|lower and item.1.enabled|default(false) and (item.1.key_server is defined or item.1.key_url is defined or item.1.key_id is defined)
  with_subelements:
    - "{{  yum_repos_default }}"
    - repositories

- name: redhat_repositories | Get extra repositories keys
  rpm_key:
    state: "{{ item.1.state | default(omit) }}"
    key: "{{ item.1.key_url | default(omit) }}"
  when: ansible_distribution|lower == item.0.distrib|lower and item.1.enabled|default(false) and (item.1.key_server is defined or item.1.key_url is defined or item.1.key_id is defined)
  with_subelements:
    - "{{ yum_repos_extra }}"
    - repositories
