---
- name: redhat_update | Yum update cache
  yum:
    update_cache: yes
  when:
    - ansible_distribution_major_version|int < 8
    - yum_repos_default_result.changed or yum_repos_lists_vaults_result.changed or yum_repos_lists_extra_result.changed or force_cache_update

- name: redhat_update | Dnf update cache
  dnf:
    update_cache: yes
  when:
    - ansible_distribution_major_version|int >= 8
    - yum_repos_default_result.changed or yum_repos_lists_vaults_result.changed or yum_repos_lists_extra_result.changed or force_cache_update

- name: redhat_update | Yum updade
  yum:
    name: '*'
    state: latest
    update_only: yes
  when:
    - ansible_distribution_major_version|int < 8
    - yum_update

- name: redhat_update | Dnf update
  dnf:
    name: '*'
    state: latest
    update_only: yes
  when:
    - ansible_distribution_major_version|int >= 8
    - yum_update
